### ISSUE TITLE
Hi RawSanj

### ISSUE THREAD

**Issue by fizz12344321** [RawSanj/RawSanj#1]
Hi RawSanj, I love all your projects, can I ask my questions here or I contact you via Linkedin, Twitter to ask.

**Comment by RawSanj** [comment]
Hi @fizz12344321,

I'm glad you liked my work, do show your support by staring my projects you like the most.

https://rawsanj.dev/#contact here you'll find multiple ways to contact me. I'm mostly active on Twitter though.
